name: Android Debug APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Point Gradle to SDK
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      # اگر sdkmanager نباشه، cmdline-tools رو دانلود و نصب می‌کنیم
      - name: Ensure sdkmanager exists
        shell: bash
        run: |
          set -e
          SDKBIN="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          if [ ! -x "$SDKBIN" ]; then
            mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
            cd "$ANDROID_SDK_ROOT/cmdline-tools"
            curl -s -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            unzip -q -o cmdline-tools.zip
            rm cmdline-tools.zip
            mv cmdline-tools latest || true
          fi

      # پذیرش لایسنس‌ها و نصب پکیج‌ها
      - name: Accept licenses & install SDK packages
        shell: bash
        run: |
          set -e
          SDKBIN="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKBIN" --licenses
          "$SDKBIN" "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # این بخش در عکسِ تو خالی مونده بود — باید دقیقاً همین‌ها باشد
      - name: Ensure Gradle wrapper
        shell: bash
        run: |
          if [ ! -f "./gradlew" ]; then
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew --no-daemon clean :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
