name: Android Debug APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Point Gradle to Android SDK
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Accept licenses & install SDK packages if sdkmanager exists
        shell: bash
        run: |
          set -e
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          if [ ! -x "$SDKMANAGER" ]; then
            SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/bin/sdkmanager"
          fi
          if [ -x "$SDKMANAGER" ]; then
            yes | sudo "$SDKMANAGER" --licenses
            sudo "$SDKMANAGER" "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          else
            echo "sdkmanager not found; will let Gradle download components."
          fi

      - name: Build (use wrapper if present; otherwise install Gradle)
        shell: bash
        run: |
          set -e
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew clean :app:assembleDebug
          else
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
            ./gradlew clean :app:assembleDebug
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
